version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db
    volumes:
      - tasks_pg_data:/bitnami/postgresql

volumes:
  tasks_pg_data: